### ISSUE TITLE
CVARS For Survivor Aim?

### ISSUE THREAD

**Issue by FirstAidHere** [Emana202/L4D2-Survivor-Bot-AI-Improver#2]
Hi. I've been testing this mod for a while and I love the improvements it gives.. Except for one thing which is being how aimbotty the AI is. They are TOO good and they can carry a lot of games by themselves. I would love for there to be a cvar or nerf to the ai aim/how fast they snap to enemys. Would make things way more balanced and fun.

**Comment by FirstAidHere** [comment]
Yo thanks for responding and actually adding a convar for this! But I think its bugged rn. I've tried deleted and reinstalling my cfg and even the entire addon the convars never appear. I copied the one on the front page of the addon and put it in my cfg but I didn't notice any effects taking place. Might be worth looking into?

**Comment by Emana202** [comment]
Updated the file. Should work rn.

**Comment by OfficerSpy** [comment]
> I tried to make them aim smoother instead of snapping immediatly at first, but when doing so their original aim overrides the new one.
> 
> I added a new convar "l4d2_improvedbots_vision_noticetimescale" that compensates that by multiplying the time to notice their target and start taking aim at it.

This may be a late suggestion, but have you tried calling `IBody::AimHeadTowards`?
