### ISSUE TITLE
New l4d2 update makes performance unbearable.

### ISSUE THREAD

**Issue by FirstAidHere** [Emana202/L4D2-Survivor-Bot-AI-Improver#20]
Game is unplayable with this plugin since newest l4d2 update. Not sure its a sourcemod thing or your mod. When removing your mod the issue goes away. Would love to see this fixed ASAP.

**Comment by Mystik-Spiral** [comment]
First... thank you Emana202 for this fantastic plugin!  However, as FirstAidHere stated, my server is inoperable after the L4D2 update from Valve yesterday (18-May-2023).  I suspect it may need a gamedata (l4d2_improved_bots.txt) update as many offsets have changed.  I have already installed the [new gamedata for left4dhooks](https://forums.alliedmods.net/showpost.php?p=2804627&postcount=880) but it does not help with this plugin.  When I disable this plugin, my server performance goes back to normal and there are no errors... but I miss the massively improved bots.

**Comment by FirstAidHere** [comment]
> 

Def needs a gamedata update. Really hope this can get fixed I miss the bots SO much right now. As Spiral said this is a fantastic plugin and one even if it isn't maintained I wish gets at least some patches.

**Comment by Emana202** [comment]
I just pushed a commit with the gamedata signature updated. Could one of you check if the problem is gone?

**Comment by Mystik-Spiral** [comment]
@Emana202 I tested this new release too and it is working better than before.  Thank you, thank you, thank you!
