### ISSUE TITLE
Invalid edict (165 - 165)

### ISSUE THREAD

**Issue by Mystik-Spiral** [Emana202/L4D2-Survivor-Bot-AI-Improver#24]
As always, thank you @Emana202 for your awesome plugin!
I am using the latest version of your plugin and seeing the following in the SM error log:

L 05/24/2023 - 00:14:49: [SM] Exception reported: Invalid edict (165 - 165)
L 05/24/2023 - 00:14:49: [SM] Blaming: l4d2_sb_ai_improver.smx
L 05/24/2023 - 00:14:49: [SM] Call stack trace:
L 05/24/2023 - 00:14:49: [SM]   [0] GetEdictClassname
L 05/24/2023 - 00:14:49: [SM]   [1] Line 4855, \\NEO\L4D2_server\left4dead2\addons\sourcemod\scripting\l4d2_sb_ai_improver.sp::SurvivorHasShotgun
L 05/24/2023 - 00:14:49: [SM]   [2] Line 3209, \\NEO\L4D2_server\left4dead2\addons\sourcemod\scripting\l4d2_sb_ai_improver.sp::L4D2_OnFindScavengeItem
L 05/24/2023 - 00:14:49: [SM]   [4] Call_Finish
L 05/24/2023 - 00:14:49: [SM]   [5] Line 3474, l4dd\l4dd_forwards.sp::DTR_SurvivorBot_FindScavengeItem_Post

**Comment by Emana202** [comment]
Pushed an update. This and the upgradepack issue should be fixed.
