### ISSUE TITLE
Survivors bots are unable to keep 4 chainsaws in the chainsaw massacre mutation

### ISSUE THREAD

**Issue by Yisus89** [Emana202/L4D2-Survivor-Bot-AI-Improver#5]
The chainsaw massacre mutation has this issue (unrelated to this plugin) where along with the 4 chainsaws, the game also spawns 4 pistols. The issue here is that despite having set these cvars for this mutation:

`l4d2_improvedbots_melee_chainsaw_limit "4"
l4d2_improvedbots_melee_max_team "4"
l4d2_improvedbots_changeweaponiftoomanysubtype_primaries "0"`

the bots still try to pick up the pistols over and over. 2 survivors can hold the chainsaw but the other 2 will endlessly switch between pistol and chainsaw. This happens despite having set the chainsaw limit to 4. 

There's no crash happening here, or any major problem. Bots are just not able to decide between chainsaw and pistol and keep switching back and forth.

**Comment by Emana202** [comment]
Could you check if the cvars are set to the right values when that happens? Because I remember when I was testing and tried to enable sv_cheats in map created in menu, it would reset the cvars' value to their default ones.

**Comment by Yisus89** [comment]
It turns out the gamemode config loader was not actually loading anything as I tested other cvars that were supposed to be changed and were not. Manually typing `sm_cvar l4d2_improvedbots_melee_chainsaw_limit "4"` correctly makes bots pick up all the chainsaw.

Now the issue is that because this https://forums.alliedmods.net/showthread.php?p=834731 doesn't seem to work, there needs to be another way to set up the cvar automatically on this gamemode. 

If it's not too much trouble for you, it would be cool if you added a check in the plugin that checks if the string mp_gamemode contains "mutation5" (the chainsaw mutation), and automatically force bots to pick all the chainsaw by changing the cvar amount or however you wish to do it. Only for this mutation of course. Check if mp_gamemode contains "mutation5" and either force a cvar change there or use another method that you prefer. 

Having this integrated right in the plugin would be much more efficient than having to write a new plugin and have it execute separately. Thanks.
